#! /bin/bash
pushd ftp
echo -n 'Login as: '
cat ../release/userid
echo 'FTP commands after login:'
echo
echo 'cd ddrs.org.uk'
echo 'mput *'
echo 'bye'
ftp -p -i ddrs.org.uk
popd
echo
echo 'If transfer was successful: rm ftp/*'

