#! /bin/bash
pushd ftp
userid=`cat ../release/userid`
echo 'FTP commands after login:'
echo 'put * .'
echo 'bye'
sftp sftp://${userid}@ddrs.org.uk:221/ddrs.org.uk
popd
echo
echo 'If transfer was successful: rm ftp/*'
cat release/reminder
